### ISSUE TITLE
EDIT exits with Out of Memory error $7F

### ISSUE THREAD

**Issue by patrickbst** [A2osX/A2osX#112]
When editing a new or existing file, adding too much text will cause EDIT to exit immediately and issue a [$7F]:Out of Memory. error when that is known not to be case (22K free, empty file so not large).  This can be reproduced by doing EDIT NEWFILE and typing random lines until you type the 512th byte.  The Error will occur.  It occurs after some number of new bytes on existing files (less then 512 typed, but length at the time was not /512).

**Comment by xandark** [comment]
I can confirm this in 1694.

**Comment by burniouf** [comment]
Partial Fix in #1700, wil rewrite buffer manager to speed up things

**Comment by patrickbst** [comment]
Updated, the out of memory error now does not happen until you exceed adding 2K of text to a new or existing file.  Given this, edit is now capable of handling most routine file editing tasks but will need to be fixed longer term.  As such, changing this to a 0.94 issue as current capabilities are ok for 0.93 release.

**Comment by patrickbst** [comment]
Tested with 1736, not crash out of EDIT occurs when you add 4K of text.

**Comment by patrickbst** [comment]
Tested in latest build 1920, can edit IFNUMTEST the largest script we have (at 11K).  No out of mem errors.  Closing issue.
