### ISSUE TITLE
STAT Command

### ISSUE THREAD

**Issue by patrickbst** [A2osX/A2osX#124]
We could use a STAT command to display extended information about a file or directory.
This command should return:
File:  "/full/path/and/filename"
Size:  78777 .  Blocks:  157  (Seedling/Sapling/Tree)   File Type: TXT
Index Block:  98233 . <--first block of file on disk
Access: 0640/-rw-r-----  .  UID: 0/root . GID: 1000/User
Modify:  19-12-25 09:34:22
Create:   19-11-11  14:11:54

Valid switches are:
-C "format string" to output one or more of the above data elements using %a %A %b %f %F %g %G %i %n %s %u %U %x %X %y %Y . The format string may contain \n to separate responses on lines. Repeating the above but substituting this symbols:
File:  %n
Size:  %s .  Blocks:  %b  (%f)   File Type: %F
Index Block:  %i
Access: %a/%A  .  UID: %u/%U . GID: %g/%G
Modify:  %x %X
Create:   %y  %Y
Note however, that if you specify any of these parameters, then only the text and parameters you pass to stat will be output, so to reproduce the first two lines from above you would:
STAT -c "File:  %n\nSize:  %s  Blocks:  %b  (%f)   File Type: %F\n" somefile

**Comment by patrickbst** [comment]
This command has been implemented.  Documentation has been written, however, according to the command, the -M option does two conflicting things, display the Mod Flags  and/or display the Modification date/time.  Running the command with **ANY** option returns garbage and never the correct/expected information.

**Comment by peterferrie** [comment]
display bug was fixed in 9d0896a92f27bf6f81031d6828ddb02982881fee

**Comment by bernstbj** [comment]
will close out in next build

**Comment by bernstbj** [comment]
Fixed as of build 2651.
