### ISSUE TITLE
FUNCTION documentation needs work

### ISSUE THREAD

**Issue by xandark** [A2osX/A2osX#134]
In the Shell Developers Guide, the FUNCTION has a paragraph where everything after the 1st sentence does not clarify but rather confuses me.

> if you SET -F, it will discard ALL previously learned FUNC in the current SH context if . FUNCS1 file add 3 then . FUNCS2 file add 2 all 5 are available until an set -X is met if you launch . MYFILE1, the code within MYFILE1 can CALL all 5 functions but MYFILE1 (wthout dot) will run in a separate SH process, so no access to the 5 functions known by parent SH functions bodies are stored in AUX ram so you can put around 30k of code in AUX ram then do a short MYFILE1 that calls a lot of FUNC in AUX FUNCs recursion is allowed (until you explode the stack!)
> 
> CORE.STACK.MAX = 128....so each CALL consumes about 7 bytes of stack (return Ctx/Ptr, ArgVC,hArgV and CALL keywordID)

Can this be edited for clarity? Before this advanced nuance about FUNCTION, I'd also like to see some examples of how to make a function and how to call it.

**Comment by patrickbst** [comment]
Function documentation has been fixed and an example has been provided for function.  Closing.
