### ISSUE TITLE
Useradd Not found

### ISSUE THREAD

**Issue by mickeylawless** [A2osX/A2osX#150]
![image](https://user-images.githubusercontent.com/64372411/80314626-9155a080-87c0-11ea-8447-8d96f1689f3b.jpg)
When logging in the command line prompts you to create a password for root since there is no etc/passwd. When I type in user add and the parameters it says “[$46]:File Not Found”.  I looked in the /bin/ where it should be located and it is not there. I downloaded both the Stable and Release 140K

**Comment by patrickbst** [comment]
Mickey, there are several media types available to download for A2osX that include images for 140K, 800K and 32mb.  The image you used above is for a 140K floppy, which unfortunately does not contain enough space to include every file that is part of A2osX.  This is why that image is called "miniboot", it contains the minimum amount of files needed to run and use A2osX.   If you can use one of the other images you will find they contain those commands (as well as others).  If the next release (0.94), we are planning on having an "install" set that will have a boot disk and then all the extras on supplemental disks that will be installed on a user specified hard drive.

**Comment by patrickbst** [comment]
I should note, that if you wanted to use the commands useradd and userdel to see how they worked and you didnt need other parts of A2 (such as networking).  You could load up the images into ciderpress and copy the files from the 800K media to the 140K miniboot.

**Comment by patrickbst** [comment]
Update: I have created a new RELEASE.140D2.po image with a volume name of /extras that contains all of the files (bins, libs, etcs, sys/km, etc) from this release not found on /miniboot.  If you place this image on drive 2, you can move files between disks as you need.  Note, you can update PATH in your profile to search the bin directories on both disks, though it is better to have the most commonly used ones on the first floppy.
