### ISSUE TITLE
set foo goes into a looping behaviour

### ISSUE THREAD

**Issue by xandark** [A2osX/A2osX#155]
With 2124 if I type, `set foo`, it goes into a looped output debug behaviour that can't be stopped.

![a2osx set foo](https://user-images.githubusercontent.com/5048913/86983109-caef4400-c13f-11ea-9925-845231e7bce5.png)

**Comment by burniouf** [comment]
ouch!!!
this one is here for a long time....
fixed in #2128

**Comment by xandark** [comment]
Just verified, fixed.
