### ISSUE TITLE
edit issue with small files

### ISSUE THREAD

**Issue by fluxo-gs** [A2osX/A2osX#169]
Editing a small file such as /FULLBOOT/etc/issue results in missing data on the screen and incorrect cursor positioning.

**Comment by patrickbst** [comment]
This is a confirmed and reproducible bug. Assign to Remy and mark for 0.94.

**Comment by patrickbst** [comment]
Fixed as of build 2460. Closing.

**Comment by fluxo-gs** [comment]
There are still some issues here, with 2460, if I go to the very last line in the file and hit backspace, the previous line vanishes. I will post a video in the slack channel.

**Comment by patrickbst** [comment]
Confirmed, have seen multiple problems with EDIT in current builds, especially with small files.  In one case I saw a small file include all the text from a large file i had just opened with edit but did not save.  Repeating the same steps over again does not produce the same results (hard to pin down an "example" problem), but often extra chars get added to saved files.

**Comment by bernstbj** [comment]
Appears to no longer be an issue as of build 2642. Attempted to create, edit, and modify a number of small files and do not see any corruption. I recall seeing corruption issues in the past, but those had been fixed some time ago, so perhaps this issue was realted.
