### ISSUE TITLE
Add support for A2Heaven 2c DCLOCK to ProDOS FX.

### ISSUE THREAD

**Issue by patrickbst** [A2osX/A2osX#172]
(http://www.a2heaven.com/webshop/index.php?rt=product/product&product_id=146) which gives me a battery-backed up ramdrive in slot 4, plus a DClock RTC
bout DCLOCK : found some doc, it is a DS1215 chip so adding a driver for it in ProDOS.FX is trivial....only info missing is  : "how do i detect A2Heaven in Slot4 ?" ROM signature ?  : "//c specific ?"
The ROM for handling the //c's expansion RAM slot is present, whether there's a RAM card installed or not.
if //c, then checking DS1215 signature at $C0C0/C1/C2 = $000080 is enough ? (edited) 
As for //c-specific - sort of?  The //c expansion RAM slot is basically an Apple Slinky RAM card integrated into the //c hardware and ROM.
So any check for its presence will likely also succeed (on a "slotted" Apple II) if there's an Apple Slinky RAM card in slot 4. (edited)

**Comment by burniouf** [comment]
Included since BUILD 2519.
Please review & close.

**Comment by burniouf** [comment]
Included since BUILD 2519.
Please review & close.

**Comment by burniouf** [comment]
ProDOS.FX now supports the following clocks :
- IIgs "Cortland " (CClk)
- A2Heaven //c DS1215 (DClk)
- No Slot Clock "NSC" (NClk)
- Thunder (TClk)
- ROMXce Clock (XClk)
