### ISSUE TITLE
lance gs autorelease

### ISSUE THREAD

**Issue by ksherlock** [A2osX/A2osX#174]
https://github.com/A2osX/A2osX/blob/30076371294ea567778201d78bdbd35f50b96b62/INC/NIC.91C96.I.txt#L34-L35

This should be:
```
 L91C96.1.CTR.DEFAULT .EQ %00000001.00000000
 L91C96.1.CTR.AUTOREL .EQ %00001000.00000000
```

The default isn't necessary

**Comment by burniouf** [comment]
Fixed since BUILD 2519.
Please review & close.

**Comment by ksherlock** [comment]
I've verified it's working as expected with MAME/apple2gs (bleeding edge version)
