### ISSUE TITLE
A series of beginner's questions 

### ISSUE THREAD

**Issue by ghost** [A2osX/A2osX#180]
Hello
I have been following this project for some time but only now have I found the time to try it seriously. Obviously I have several questions to ask,
Let's go in order
1) the A2OSX.BUILD.po disk image has several allocated blocks which do not belong to any file, could it be corrupted?
2) can one disable the call to the DHCP server? I prefers to have the network under control and assign addresses to the various devices "by hand"
3) I understand that the kernel modules are identified as pm.* Even if in the documentation they are km.* The question however is which do you think is the best way to not load the ones I don't need (for example pm.vsdrive ) rename them, move them to another directory, is there a specific command that I haven't found?

I am following the development of the C compiler with real interest!

Thank you

Marco

**Comment by burniouf** [comment]
Hello,
best place to answer your "beginner" question is there:

https://join.slack.com/t/a2osx/shared_invite/zt-ens62cl0-xeAFLjlRfUSMtzdc6o~Xew

(you will be able to kick some asses of those who are responsible to update documentation ;-)

**Comment by DocDoom99** [comment]
Ok, continue on Slack.
Marvin could have said: Documentation? Don't talk to me about documentation.
Real programmers, if they really have to, write it as the last thing 

Marco
