### ISSUE TITLE
sed should accept STDIN in addition to file input

### ISSUE THREAD

**Issue by bernstbj** [A2osX/A2osX#196]
This doesn't work:
```
$ echo "foo" | sed s/foo/bar/ 
```

You have to do this:
```
$ echo "foo" > tmpfile
$ sed s/foo/bar/ tmpfile
```

Would be great if it accepted STDIN so it could be chained!

**Comment by burniouf** [comment]
Already supporting PIPing ....

**Comment by xandark** [comment]
maybe this will be fixed as show in #198 ?

**Comment by burniouf** [comment]
Fixed since....a long time....please review & close

**Comment by bernstbj** [comment]
Confirmed for build 2642.
