### ISSUE TITLE
echo issue

### ISSUE THREAD

**Issue by xandark** [A2osX/A2osX#198]
With the latest build I'm getting this:

```
$ echo "this is a test" | cut -F 2
[$28]:No Device
```

Also, if I type cut without any arguments, press Enter, I cannot get out of cut's grip. I can't ctrl-c or ctrl-d, I'm stuck.

Under GNU/Linux, cut without arguments gives me:

```
cut: you must specify a list of bytes, characters, or fields
Try 'cut --help' for more information.
```

**Comment by burniouf** [comment]
ECHO issue, instead....works fine from a cat file | cut -F 2

**Comment by burniouf** [comment]
Fixed in next BUILD (with many other PIPE related bugs)
![image](https://github.com/A2osX/A2osX/assets/8941204/eacdf1e0-f77a-4e1c-891f-10bfda7c0da0)
