### ISSUE TITLE
IPCONFIG could return error codes based on state

### ISSUE THREAD

**Issue by bernstbj** [A2osX/A2osX#199]
Under MAME, you have to run ipconfig several times over 1-2 minutes until MAME finally resolves the network for a2osx. As such, you keep getting timeouts and no network. It would be nice to have a script that would repeatedly run ipconfig until it actually obtains an IP address, but it requires juggling a few other tools at this point. Maybe ipconfig could return error codes based on success/failure?  e.g. 0=all good, 1=no network stack, 2=timeout, 3=other?

**Comment by burniouf** [comment]
.95 : Retries have been added to IPCONFIG to solve this issue.
Please review & close

**Comment by bernstbj** [comment]
appears to be working as of build 2642.
