### ISSUE TITLE
How to put A2osX in a 4MB (8192 blocks) file.

### ISSUE THREAD

**Issue by rallepalaveev** [A2osX/A2osX#200]
Hi,

I tried to transfer the system from 32MB ProDOS .po file to a 4MB ProDOS .po file, so it can fit on the 4MB NVRAM drive (which I develop), but the system freezes at "Reading Kernel Config File". I renamed the file PROFILE to .PROFILE, which could not copy correctly, but still I get stuck at this stage. Any hints please?

**Comment by burniouf** [comment]
will this media boot ProDOS.FX ?
in that case you must use ProDOS.FX to copy files to it, because ProDOS.FX is case sensitive, and allows extended filenames like ".profile" (lowercase, starting with a ".")
Best way is to boot STABLE.32MB.po media, format 4MB.po and cp -r * to it

**Comment by rallepalaveev** [comment]
Hi, thanks for your reply.

Yes, it is bootable media and I run ProDOS from it (Link: https://github.com/rallepalaveev/Prodos-4MB-NVRAM-Drive

I will run ProDOS.FX as suggested, so hopefully that would do the trick!

Thanks!

Ralle.

**Comment by burniouf** [comment]
Let me know if you get issues using ProDOS.FX
it has a lot of enhancement over ProDOS 2.0.3, specially around BLK devices (advanced remap...etc...)

**Comment by rallepalaveev** [comment]
I apologize is I am asking a stupid question, but how do I mount the new 4MB disk? Is there any specific procedure? I am influenced by Linux and urged to do a cat /proc/partitions and then a mount /dev..., but I guess it is not the case.

**Comment by rallepalaveev** [comment]
Hi,

"cp -r *" worked nicely and I managed to copy all files from the 32MB image to my 4MB one!

I did not encounter any issues with ProDOS.FX

Many thanks!

R.

**Comment by burniouf** [comment]
does ProDOS.FX/A2osX  boot properly from your device ?

**Comment by rallepalaveev** [comment]
Hi, I have been just testing on an emulator to create an image. I will soon test it and post the results.

One thing I noticed is that some files are just not seen when listing the directory from within ProDOS. If I put QUIT.SYSTEM, then I see a list of files and folders, which I can be browsing and executing. If a file is of type 06 (BIN) it is not displayed, as if not existing. If I quit to BASIC.SYSTEM, then when I browse I can reach the files and execute them.

R.

**Comment by burniouf** [comment]
Please join :

https://join.slack.com/t/a2osx/shared_invite/zt-ens62cl0-xeAFLjlRfUSMtzdc6o~Xew

easier to track your issue there...
