### ISSUE TITLE
ProDOS.FX QUIT code not displaying files

### ISSUE THREAD

**Issue by rallepalaveev** [A2osX/A2osX#201]
The ProDOS.FX QUIT code seems to be displaying folders and SYSTEM files ($FF), which can be executed, while other executable files like BIN and BAS are not displayed and cannot be executed.

Propose to add to the files being displayed types $06, $FA, $FC and $FD.

**Comment by patrickbst** [comment]
I think that is something in QUIT, not related to ProDOS FX or other versions.  ProDOS wants to load a system file after it boots.  The quit.system just allows you to chain to another .SYS type file.  You can't chain to a BAS file for example as you need to load BASIC.SYS (a system file) to run a Basic program.  This is probably not at all an FX problem but just the way the QUIT.SYS works.  Might want to ask John Brooks for verification.

**Comment by rallepalaveev** [comment]
Thank you. Just an observation - the QUIT system in 2.4.2 displays all files, independent of their type. Will ask as suggested.

**Comment by burniouf** [comment]
.95 Done. Added .BIN & .BAS files to be launched if BASIC.SYSTEM found in some browsed volume
Please review & close
