### ISSUE TITLE
md5 with no arguments says syntax error

### ISSUE THREAD

**Issue by xandark** [A2osX/A2osX#202]
version 2600

![Screenshot 2023-06-16 (21∶58∶24)](https://github.com/A2osX/A2osX/assets/5048913/fcaf1d46-d95e-437b-8e1b-a3b61d57b73e)

**Comment by burniouf** [comment]
Normal Behavior, execpt "\r\n" not processed properly.
All commands return "Syntax Error" and usage if missing/invalid parameters

**Comment by burniouf** [comment]
many "\r\n" issues corrected in latest commit, included MD5

**Comment by xandark** [comment]
Yes, after testing with the latest commit, the \r\n issue isn't there in md5.
