### ISSUE TITLE
seq doesn't interpret the \r\n escape outputs but prints them literally

### ISSUE THREAD

**Issue by xandark** [A2osX/A2osX#203]
from latest commit in A2OSX.BUILD.po

![Screenshot 2023-06-17 (14∶39∶18)](https://github.com/A2osX/A2osX/assets/5048913/5c80a8d9-789e-455a-9edf-67bba03c4364)

**Comment by burniouf** [comment]
![image](https://github.com/A2osX/A2osX/assets/8941204/7fd17089-181f-4aa3-9f03-7b9774d82df9)
added some enhancement ;-)

**Comment by xandark** [comment]
Why does the first version that just has the "\r" separator not print anything?

**Comment by burniouf** [comment]
because it prints "1" then it is erased.....then "10" erased by \r 
Normal behavior

**Comment by burniouf** [comment]
@xandark please join SLACK testing channel....you will get latest status of bug fixes, this will prevent you to hit already fixed bugs

https://join.slack.com/t/a2osx/shared_invite/zt-ens62cl0-xeAFLjlRfUSMtzdc6o~Xew
