### ISSUE TITLE
2642-MV reports $40 Invalid Path in moving a file to a subdirectory

### ISSUE THREAD

**Issue by bernstbj** [A2osX/A2osX#206]
Simple file 'boooo' wanting to be moved to 'bin', but reports a failure. Tried to echo an old bug on filename length by subsequently creating a subdirectory 'binnnn', but that failed too as seen below:

```
/BLANK140/$ ls -l
d---------     0     0              <dir>    16:34:00  16:34:00 bin/
----------     0     0          68 txt       16:42:00  16:34:00 fah
----------     0     0          68 txt       16:50:00  16:50:00 boooo
/BLANK140/$ mv boooo bin
MV File:/BLANK140/boooo to /BLANK140/bin/boooo...[40]
[$40]:Invalid Path.
/BLANK140/$ mkdir binnnn
/BLANK140/$ mv boooo binnnn
MV File:/BLANK140/boooo to /BLANK140/binnnn/boooo...[40]
[$40]:Invalid Path.
/BLANK140/$
```

**Comment by bernstbj** [comment]
Might be related to existing MV issue which doesn't appear fixed:  [https://github.com/A2osX/A2osX/issues/53](https://github.com/A2osX/A2osX/issues/53)

**Comment by peterferrie** [comment]
6340bc77fda0377c63b9c84db411e3c2589dbbda fixes it for me

**Comment by peterferrie** [comment]
might also be fixed by 6340bc77fda0377c63b9c84db411e3c2589dbbda

**Comment by bernstbj** [comment]
@peterferrie - totally fixed by https://github.com/A2osX/A2osX/commit/6340bc77fda0377c63b9c84db411e3c2589dbbda .. will close this out shortly. thank you!

**Comment by bernstbj** [comment]
fixed as of build 2651.
