### ISSUE TITLE
2642-Edit corruption once file reaches 2048 bytes

### ISSUE THREAD

**Issue by johnlefebvre** [A2osX/A2osX#207]
Using edit from shell:
Editing a file, once the file len goes above 2047 bytes (any method, typing or pasting), the first 2048 bytes of text disappears and the remaining text is on line one of the file.  
This has the effect that if the cursor was beyond line 1 it is now in a dead space and cannot move.
The menus such as Ctrl-A and Ctrl-Q still work but the filename can also get corrupted if it is an existing loaded or saved file.
Using Build 2642 (stable 32mb)

**Comment by bernstbj** [comment]
https://github.com/A2osX/A2osX/assets/11576313/6f194a66-164c-4550-8014-ef1f546ad432

confirmed it seems to die around the 2k mark. repeatable.

**Comment by bernstbj** [comment]
fixed as of build 2651.
