### ISSUE TITLE
FOR loop crashes on LOOP ending

### ISSUE THREAD

**Issue by bernstbj** [A2osX/A2osX#210]
Using a FOR statement in the shell and ending with a LOOP causes a crash.

```
*** A2osX-Login ***

No ETC/PASSWD file present, Logged as ROOT.
Consider adding ROOT user with USERADD command.

*** MOTD ***

Welcome to A2osX 0.95

A2osX-SH 0.95

root@/A2OSX.BUILD/root/$ for i in `seq 5` ; echo "i=$i" ; loop
i=1
for i in `seq 5` ; echo "i=$i" ; loop
-------------------------------------^
Line #1:[$C4]:LOOP Without WHILE.

^
FF/00B3:
FF/4689:
FF/3638:
FF/36FF:

```

FWIW, the `FF/36FF:` stuff at the end is the IIgs crash output.

**Comment by burniouf** [comment]
![image](https://github.com/A2osX/A2osX/assets/8941204/53d87d9e-0b72-40ca-93d3-3ceeba04660a)
FOR / NEXT, Brian.....not FOR LOOP ;-)
but a bug/crash still here in case of SYNTAX ERROR

**Comment by burniouf** [comment]
![image](https://github.com/A2osX/A2osX/assets/8941204/218a5d32-760c-45bf-9fa7-75755c820099)
LOOP fixed (in case of silly mistakes in scripts done by BJB)

**Comment by bernstbj** [comment]
Will test and close with next media release

**Comment by bernstbj** [comment]
Released in build 2666
