### ISSUE TITLE
MV doesnt move files

### ISSUE THREAD

**Issue by patrickbst** [A2osX/A2osX#53]
MV Dir1 Dir2  results in 0 Files Moved.  I tried full path names, paths with and with out beg/end /

From XLS 156

**Comment by patrickbst** [comment]
RG responds:  MV -R is required to cp/mv/rm DIRs

**Comment by patrickbst** [comment]
if you are just trying to rename a dir and not really moving everything you should be able to do that with MV.  i.e. if there is a volume with the name /MYVOL that has a subdir name AWORKS and below that is all of appleworks installed and you want to change it to AWORKS3, you should be able to MV AWORKS AWORKS3 to change its name.  Also the way -R works.  If you try to MV /MYVOL/AWORKS to /RAM3, it doesnt do what you think which is move AWORKS to be /RAM3/AWORKS,   This needs more DOC and discussion.

**Comment by burniouf** [comment]
fixed in 1403, but src folder not properly deleted when empty

**Comment by patrickbst** [comment]
Tried MV dir in 1448.  Copied /BUILD/* to /RAM3.  Then CD to /RAM3 and tried a MV ROOT ROOT2.  My expectation was along the lines of a simple rename of ROOT to ROOT2 even if it did this via CP/DEL of the files and dirs.  The output of the command was:
/RAM3/$ MV -R ROOT ROOT2                                                        
MV Dir :/RAM3/ROOT to /RAM3/ROOT2...[OK]                                        
MV Dir :/RAM3/ROOT/ASMTEST to /RAM3/ROOT/ROOT2...[OK]                           
MV File:/RAM3/ROOT/ASMTEST/A1 to /RAM3/ROOT/ASMTEST/ROOT2...[OK]                
MV File:/RAM3/ROOT/ASMTEST/A2 to /RAM3/ROOT/ASMTEST/ROOT2...                    
Overwrite /RAM3/ROOT/ASMTEST/ROOT2 [Yes,No,All]?[47]                            
MV -R ROOT ROOT2                                                                
----------------^                                                               
Line #1:[$47]:Duplicate Filename.                                               
As you can see it was nowhere close to moving the dir correctly.

**Comment by patrickbst** [comment]
Just tried with 1728.  Copied /FULLBOOT to /RAM4.  cd /RAM4.  there is the ROOT dir.  did a MV ROOT ROOT2 (trying to do basically a ren).  says no file copied.  This is probably ok (since REN command exists), but want to confirm this is right behavior.  Then did MV -R ROOT ROOT2.  ROOT contains 2 files PROFILE and NET.  MV created the ROOT2 dir then when it said it said it was doing a MV File . /RAM4/ROOT/PROFILE to /RAM4/ROOT/ROOT2. and then NET to ./ROOT/ROOT2 (hence the overwrite).  i ended with an empty ROOT2 and in ROOT, was ROOT2 (the old PROFILE) and NET (since i said no to overwrite).

**Comment by patrickbst** [comment]
A note for people reading this issue...  This bug affects both *mv* and *cp* and involves only moves/copies when you are doing a recursive operation (-R) and the destination does not yet exist.  for instance if you boot A2osX (say /fullboot) and CD to /fullboot and then attempt to cp -R * /mydrive/a2osx.  Here you want to copy everything on the volume fullboot, recursively and put it in a new folder called a2osx on the volume mydrive.  What happens is that the bug in the command causes them to keep doing the moves/copies to a single file (prompting you to overright) and the file name is wrong.  To work around this problem, first do a *md /mydrive/a2osx* and then perform the copy or move as normal and all will behave normally.  This bug will be resolved in 0.94

**Comment by patrickbst** [comment]
Moving to 0.94.  Will label this as a known bug for 0.94 release and put in ReadME or UserGuide and then move to 0.95 for fix.

**Comment by bobbimanners** [comment]
Needs to check destination is one of:
- An existing file (in which case error if the source is a wildcard?)
- An existing dir (in which case copy files to dir)
- Doesn't exist (in which case will attempt to create dir)

**Comment by bernstbj** [comment]
Tested on build 2642 and appears to still be an issue.

```
/RAM5/$ ls -la
d---------     0     0              <dir>   <no-date> <no-date> ./
d---------     0     0              <dir>    11:28:00  11:28:00 root/     <-- full copy of ${ROOT}/root
/RAM5/$ mkdir root2
/RAM5/$ ls -la root2
d---------     0     0              <dir>   <no-date>  11:31:00 ./
d---------     0     0              <dir>   <no-date>  11:31:00 ../
/RAM5/$ mv -r root/* root2
MV Dir :/RAM5/root/acostest to /RAM5/root2/acostest...[OK]
MV File:/RAM5/root/acostest/bbs.a to /RAM5/root2/acostest/bbs.a...[40]
[$40]:Invalid Path.
/RAM5/$ ls -l root2
d---------     0     0              <dir>    11:31:00  11:31:00 acostest/
/RAM5/$ ls -l root2/acostest
/RAM5/$

```

**Comment by peterferrie** [comment]
6340bc77fda0377c63b9c84db411e3c2589dbbda fixes this for me

**Comment by bernstbj** [comment]
will close out in next build

**Comment by bernstbj** [comment]
fixed as of build 2651.
