### ISSUE TITLE
SHUTDOWN Command

### ISSUE THREAD

**Issue by patrickbst** [A2osX/A2osX#83]
There should be a shutdown command that closes open sockets, open files, executes ETC/INIT0 script and then does standard ProDOS exit (loads bitsy.bye type thing).  IS that what QUITCODE is?
--From S0028

**Comment by patrickbst** [comment]
RG: SHELL will handle SYS files, calling API shutown with arg=.SYS file this will pass .SYS file to A2osX QC
Yes there is an A2osX special version of QuitCode, See documentation.

**Comment by patrickbst** [comment]
Modify shutdown system so that if a user issues a command like **myapp.system  afile aparm** it will place the parameters **afile** and **aparm** into the ProDOS argument buffer space which myapp.system can check and use at startup as supported by CC65 and DaveX.

**Comment by bernstbj** [comment]
Confirmed working as of build 2642.
