### ISSUE TITLE
RMDIR

### ISSUE THREAD

**Issue by patrickbst** [A2osX/A2osX#86]
Like   there is MKDIR alias for MD, there should be an alias RMDIR for RD.  BTW, why is MKDIR BIN?  What extra is there as a bin rather then a   script? Like L is to LS.
--From S0032

**Comment by burniouf** [comment]
MD can only create an extra level of SUBDIR in an existing DIR.
You cannot do a MD DIR1/DIR2/DIR3 on a blank media
MKDIR should do that...

**Comment by burniouf** [comment]
MKDIR now handles -P switch to create DIR/1/DIR2/DIR3.....
